Unify "sqlite3" gem version with it used in "activerecord" gem
In activerecord `6.0.3.4` uses sqlite3 `1.4.x`. It needs to unify the versions to run tests.

Warning was:
```
$ bundle _1.16.6_ exec rspec

bundler: failed to load command: rspec
(/Users/machupicchubeta/Repositories/github.com/machupicchubeta/shiroyagi/vendor/bundle/bin/rspec)
LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-1.3.13. Make sure all dependencies are added to Gemfile.
```

See also:
- https://github.com/rails/rails/blob/v6.0.3.4/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L13